version: '3.4'

services:

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
      - "14331:1433"
  
  #sqldb:
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  #  environment:
  #      - SA_PASSWORD = "Test@1234"
  #      - ACCEPT_EULA = "Y"
  #  ports:
  #      - "1440:1433"
